Repository TEdit/Terraria-Map-Editor, pull requests merged in 2024-07, with the labels that each got.

#1903 Fix Tile Selection Dropdown
  src/TEdit/Framework/XamlConverters.cs
  src/TEdit/Themes/Templates.xaml
  src/TEdit/ViewModel/WorldViewModel.Editor.cs
  src/TEdit/ViewModel/WorldViewModel.cs
Labels: bug, Semver-Patch

#1906 Fix for UndoManager Crash
  src/TEdit.Desktop/App.axaml.cs
  src/TEdit.Desktop/Editor/IMouseTool.cs
  src/TEdit.Desktop/Program.cs
  src/TEdit.Desktop/TEdit.Desktop.csproj
  src/TEdit.Desktop/ViewModels/DocumentViewModel.cs
  src/TEdit.Desktop/ViewModels/MainWindowViewModel.cs
  src/TEdit.Desktop/ViewModels/ToolSelectionViewModel.cs
  src/TEdit.Desktop/Views/DocumentView.axaml
  src/TEdit.Desktop/Views/MainWindow.axaml
  src/TEdit.Desktop/Views/MainWindow.axaml.cs
  src/TEdit.Desktop/Views/PaintModeView.axaml
  src/TEdit.Desktop/Views/PaintModeView.axaml.cs
  src/TEdit.Editor/WorldEditor.cs
  src/TEdit/ViewModel/WorldViewModel.cs
Labels: bug

#1927 Many Features Added, SimpleOreGenerator Rehaul, Many TE Bug Fixes, And More!
  src/TEdit.Editor/WorldEditor.cs
  src/TEdit.Terraria/World.Properties.cs
  src/TEdit/Editor/Plugins/RemoveTileWithPlugin.cs
  src/TEdit/Editor/Plugins/ReplaceAllPlugin.cs
  src/TEdit/Editor/Plugins/SimpleOreGeneratorPlugin.cs
  src/TEdit/Editor/Plugins/SimpleOreGeneratorPluginView.xaml
  src/TEdit/Editor/Plugins/SimpleOreGeneratorPluginView.xaml.cs
  src/TEdit/Editor/Plugins/SimplePerlinGeneratorPlugin.cs
  src/TEdit/MainWindow.xaml.cs
  src/TEdit/View/Popups/NewWorldView.xaml
  src/TEdit/View/Sidebar/SpecialTileView.xaml
  src/TEdit/ViewModel/ViewModelLocator.cs
  src/TEdit/ViewModel/WorldViewModel.Commands.cs
  src/TEdit/ViewModel/WorldViewModel.cs
  src/TEdit/settings.xml
Labels: Feature, Epic, Done ✅

#1930 Added a Player .map Renderer Plugin.
  src/TEdit/Editor/Plugins/PlayerMapRenderer.cs
  src/TEdit/ViewModel/ViewModelLocator.cs
Labels: Feature, Epic
